NET TECHONOLOGY/NET TECHONOLOGY/AssetManagement/AssetManagement/Controllers/BookController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using AssetManagement.Models;
using System.Collections.Generic;

namespace AssetManagement.Controllers
{
    public class BookController : Controller
    {
        public static List<Book> BookList = new List<Book>();
        int index;
        [HttpGet]
        public ViewResult AddBook()
        {
            return View();
        }
        public ViewResult DeleteBook()
        {
            return View();
        }
        public ViewResult SearchBook()
        {
            return View();
        }
        public ViewResult UpdateBook(int id)
        {
            var update = BookList.Where(s => s.id == id).FirstOrDefault();
            return View(update);
        }
        [HttpPost]
        public IActionResult AddBook(Book book)
        {
           
            if (ModelState.IsValid)
            {
                BookList.Add(book);
                return RedirectToAction("Index", BookList);
            }
            else
                return View();

        }
        [HttpPost]
        public ActionResult DeleteBook(int id)
        {
            if(ModelState.IsValid)
            {
                
                if(BookList.Count==0)
                {
                    return View("ListEmpty");
                }
                
               Book book = BookList.Where(x => x.id == id).FirstOrDefault();
                if (book==null)
                {
                    return View("NotFound");
                    
                }
                else
                {
                    BookList.Remove(book);
                    return RedirectToAction("Index", BookList);
                }
              
              
            }
            return View();
        }
 [HttpPost]
        public ViewResult SearchBook(int id)
        {
            
            if(ModelState.IsValid)
            {
                if (BookList.Count == 0)
                {
                    return View("ListEmpty");
                }
                Book book = BookList.Where(x => x.id == id).FirstOrDefault();
                if(book==null)
                {
                    return View("NotFound");
                }
                else
                {
                    Book bookAsset = new Book()
                    {
                        id = book.id,
                        name = book.name,
                        author = book.author,
                        edition = book.edition,
                        dateOfPublish = book.dateOfPublish

                    };
                    ViewBag.bookAsset = bookAsset;
                    return View("DisplayTheSearchForBook");
                }
                              
            }
            return View();
        }
        [HttpPost]
        public ActionResult UpdateBook(Book bookId)
        {
            if(ModelState.IsValid)
            {
                if (BookList.Count == 0)
                {
                    return View("ListEmpty");
                }
                index = BookList.FindIndex(s => s.id ==bookId.id);
                if (index != -1)
                {
                    BookList[index] = bookId;
                    return RedirectToAction("index", BookList);
                }
                else
                {
                    return View("NotFound");
                }
                
            }
             return View();
            
        }

        public ViewResult Index()
        {
            return View();
        }
            
        
        
    }
}

NET TECHONOLOGY/NET TECHONOLOGY/AssetManagement/AssetManagement/Controllers/HardwareController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using AssetManagement.Models;
using System.Collections.Generic;

namespace AssetManagement.Controllers
{
    public class HardwareController : Controller
    {
        public static List<Hardware> HardwareList = new List<Hardware>();
        int index;
        [HttpGet]
        public ViewResult AddHardware()
        {
           return View();
        }
        public ViewResult DeleteHardware()
        {
            return View();
        }
        public ViewResult SearchHardware()
        {
            return View();
        }
        public ViewResult UpdateHardware(int id)
        {
            var update = HardwareList.Where(s => s.id == id).FirstOrDefault();
            return View(update);
        }
        [HttpPost]
        public ActionResult AddHardware(Hardware hardware){
                TryUpdateModelAsync(hardware);
                if(ModelState.IsValid)
                {
                    HardwareList.Add(hardware)   ;
                    
                    return RedirectToAction("Index",HardwareList);
                }
                else 
                return View();
        } 
         [HttpPost]
        public ViewResult SearchHardware(int id)
        {
            
            if (ModelState.IsValid)
            {
                if (HardwareList.Count == 0)
                {
                    return View("ListEmpty");
                }
                Hardware hardware = HardwareList.Where(x => x.id == id).FirstOrDefault();
                if (hardware == null)
                {
                    return View("NotFound");
                }
                else
                {
                    Hardware hardwareAsset = new Hardware()
                    {
                        id = hardware.id,
                        name = hardware.name,
                        brand = hardware.brand,
                        installationDate = hardware.installationDate,
                        amount = hardware.amount

                    };
                    ViewBag.hardwareAsset = hardwareAsset;
                    return View("DisplayTheSearchForHardware");
                }

            }
            return View();
        }
        [HttpPost]
        public ActionResult DeleteHardware(int id)
        {
           
            if (ModelState.IsValid)
            {
                Hardware hardware = HardwareList.Where(x => x.id == id).FirstOrDefault();
                if (hardware == null)
                {
                    return View("NotFound");

                }
                else
                {
                    HardwareList.Remove(hardware);
                    return RedirectToAction("Index", HardwareList);
                }

            }
            return View();
        }
        [HttpPost]
        public ActionResult UpdateHardware(Hardware updateid)
        {
            if (ModelState.IsValid)
            {
                if (HardwareList.Count == 0)
                {
                    return View("ListEmpty");
                }
                index = HardwareList.FindIndex(s => s.id == updateid.id);
                if (index != -1)
                {
                    HardwareList[index] = updateid;
                    return RedirectToAction("index", HardwareList);
                }
                else
                {
                    return View("NotFound");
                }

            }
            return View();
            
        }
        public ViewResult Index()
        {
            return View();
        }
      
    }
}

        

   

NET TECHONOLOGY/NET TECHONOLOGY/AssetManagement/AssetManagement/Controllers/SoftwareController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using AssetManagement.Models;

namespace AssetManagement.Controllers
{
    public class SoftwareController : Controller
    {
        public static List<Software> SoftwareList = new List<Software>();
        int index;
        [HttpGet]
        public ViewResult AddSoftware()
        {
           return View();
        }
         public ViewResult DeleteSoftware()
        {
            return View();
        }
           public ViewResult SearchSoftware()
        {
            return View();
        }
           public ViewResult UpdateSoftware(int id)
        {
            var update = SoftwareList.Where(s => s.id == id).FirstOrDefault();
            return View(update);
        }

        [HttpPost]
        public ActionResult AddSoftware(Software software){
                
                if(ModelState.IsValid)
                {
                SoftwareList.Add(software);
                return RedirectToAction("Index",SoftwareList);
                }
                else 
                return View();

        }

        [HttpPost]
        public ViewResult SearchSoftware(int id)
        {

            if (ModelState.IsValid)
            {
                if (SoftwareList.Count == 0)
                {
                    return View("ListEmpty");
                }
                Software software = SoftwareList.Where(x => x.id == id).FirstOrDefault();
                if (software == null)
                {
                    return View("NotFound");
                }
                else
                {
                    Software sofwareAsset = new Software()
                    {
                        id = software.id,
                        name = software.name,
                        dateOfPublish = software.dateOfPublish,
                        dateOfExpiry = software.dateOfExpiry,
                        price = software.price

                    };
                    ViewBag.softwareAsset = sofwareAsset;
                    return View("DisplayTheSearchForSoftware");
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult DeleteSoftware(int id)
        {
           
            if(ModelState.IsValid)
                {
                Software software = SoftwareList.Where(x => x.id == id).FirstOrDefault();
                if (software == null)
                {
                    return View("NotFound");

                }
                else
                {
                    SoftwareList.Remove(software);
                    return RedirectToAction("Index", SoftwareList);
                }

            }
            return View();
        }
        [HttpPost]
        public ActionResult UpdateSoftware(Software updateid)
        {
            if (ModelState.IsValid)
            {
                if (SoftwareList.Count == 0)
                {
                    return View("ListEmpty");
                }
                index = SoftwareList.FindIndex(s => s.id == updateid.id);
                if (index != -1)
                {
                    SoftwareList[index] = updateid;
                    return RedirectToAction("index", SoftwareList);
                }
                else
                {
                    return View("NotFound");
                }

            }
            return View();
            
        }
        public ViewResult Index()
        {
            return View();
        }
        
    }
}

NET TECHONOLOGY/NET TECHONOLOGY/AssetManagement/AssetManagement/Views/Shared/ListEmpty.cshtml
@{
    ViewData["Title"] = "ListEmpty";
}

<h1>List Is Empty</h1>

NET TECHONOLOGY/NET TECHONOLOGY/AssetManagement/AssetManagement/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NFound";
}

<h1>Asset not found in the list please enter the correct value</h1>

NET TECHONOLOGY/NET TECHONOLOGY/AssetManagement/AssetManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssetManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AssetManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" asp-controller="Home">Add</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Book" asp-action="AddBook">Books</a></li>
                                <li><a asp-controller="Software" asp-action="AddSoftware">Software License</a></li>
                                <li><a asp-controller="Hardware" asp-action="AddHardware">Hardwares</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" asp-controller="Home">Display</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Book" asp-action="Index">Books</a></li>
                                <li><a asp-controller="Software" asp-action="Index">Software License</a></li>
                                <li><a asp-controller="Hardware" asp-action="Index">Hardwares</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" asp-controller="Home">Delete</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Book" asp-action="DeleteBook">Books</a></li>
                                <li><a asp-controller="Software" asp-action="DeleteSoftware">Software License</a></li>
                                <li><a asp-controller="Hardware" asp-action="DeleteHardware">Hardwares</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" asp-controller="Home">Search</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Book" asp-action="SearchBook">Books</a></li>
                                <li><a asp-controller="Software" asp-action="SearchSoftware">Software License</a></li>
                                <li><a asp-controller="Hardware" asp-action="SearchHardware">Hardwares</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" asp-controller="Home">Update</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Book" asp-action="UpdateBook">Books</a></li>
                                <li><a asp-controller="Software" asp-action="UpdateSoftware">Software License</a></li>
                                <li><a asp-controller="Hardware" asp-action="UpdateHardware">Hardwares</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>