NET TECHONOLOGY/NET TECHONOLOGY/DbAssetManagement/DbAssetManagement/Controllers/BookController.cs
using DbAssetManagement.Data;
using DbAssetManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DbAssetManagement.Controllers
{
    public class BookController : Controller
    {
        DbAssetManagementContext context = new DbAssetManagementContext();
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Book book = context.Books.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(book);
        }
       
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            context.Attach(book);
            context.Entry(book).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Book book = context.Books.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(book);
        }
        [HttpGet]
        public IActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(Book book)
        {
            context.Attach(book);
            context.Entry(book).State = EntityState.Deleted;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Create(Book book)
        {
            context.Attach(book);
            context.Entry(book).State = EntityState.Added;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Search(int SerialNo)
        {
           
            if(ModelState.IsValid)
            {
                Book book = context.Books.Where(x => x.SerialNo == SerialNo).FirstOrDefault();
                if (book == null)
                {
                    return View("NotFound");
                }
                else
                {
                    Book bookAsset = new Book()
                    {
                        SerialNo = book.SerialNo,
                        BookName = book.BookName,
                        Author = book.Author,
                        Edition = book.Edition,
                        DateOfPublish = book.DateOfPublish

                    };
                    ViewBag.bookAsset = bookAsset;
                    return View("DisplayTheSearched");

                }
            }
            return View();

        }

        public IActionResult Index()
        {
            List<Book> books = context.Books.ToList();
            return View(books);
        }
        public IActionResult Details(int id)
        {
            Book book = context.Books.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(book);
        }
    }
}

NET TECHONOLOGY/NET TECHONOLOGY/DbAssetManagement/DbAssetManagement/Controllers/HardwareController.cs
using DbAssetManagement.Data;
using DbAssetManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DbAssetManagement.Controllers
{
    public class HardwareController : Controller
    {
        DbAssetManagementContext context = new DbAssetManagementContext();
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Hardware hardware = context.Hardwares.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(hardware);
        }

        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Hardware hardware)
        {
            context.Attach(hardware);
            context.Entry(hardware).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Hardware hardware = context.Hardwares.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(hardware);
        }
        [HttpGet]
        public IActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(Hardware hardware)
        {
            context.Attach(hardware);
            context.Entry(hardware).State = EntityState.Deleted;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Create(Hardware hardware)
        {
            context.Add(hardware);
            context.Entry(hardware).State = EntityState.Added;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Search(int SerialNo)
        {
            if (ModelState.IsValid)
            {
                Hardware hardware = context.Hardwares.Where(x => x.SerialNo == SerialNo).FirstOrDefault();
                if (hardware == null)
                {
                    return View("NotFound");
                }
                else
                {
                    Hardware hardwareAsset = new Hardware()
                    {
                        SerialNo = hardware.SerialNo,
                        HardwareName = hardware.HardwareName,
                        Brand = hardware.Brand,
                        InstallationDate= hardware.InstallationDate,
                        Amount = hardware.Amount

                    };
                    ViewBag.hardwareAsset = hardwareAsset;
                    return View("DisplayTheSearched");

                }
            }
            return View();

        }

        public IActionResult Index()
        {
            List<Hardware> hardwares = context.Hardwares.ToList();
            return View(hardwares);
        }
        public IActionResult Details(int id)
        {
            Hardware hardware = context.Hardwares.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(hardware);
        }
    }
}

NET TECHONOLOGY/NET TECHONOLOGY/DbAssetManagement/DbAssetManagement/Controllers/SoftwareLicenseController.cs
using DbAssetManagement.Data;
using DbAssetManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DbAssetManagement.Controllers
{
    public class SoftwareLicenseController : Controller
    {
        DbAssetManagementContext context = new DbAssetManagementContext();
        [HttpGet]
        public IActionResult Edit(int id)
        {
            SoftwareLicense software = context.SoftwareLicenses.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(software);
        }

        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Edit(SoftwareLicense software)
        {
            context.Attach(software);
            context.Entry(software).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            SoftwareLicense software = context.SoftwareLicenses.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(software);
        }
        [HttpGet]
        public IActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(SoftwareLicense software)
        {
            context.Attach(software);
            context.Entry(software).State = EntityState.Deleted;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Create(SoftwareLicense software)
        {
            context.Add(software);
            context.Entry(software).State = EntityState.Added;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Search(int SerialNo)
        {
            if (ModelState.IsValid)
            {
                SoftwareLicense software = context.SoftwareLicenses.Where(x => x.SerialNo == SerialNo).FirstOrDefault();
                if (software == null)
                {
                    return View("NotFound");
                }
                else
                {
                    SoftwareLicense softwareAsset = new SoftwareLicense()
                    {
                        SerialNo = software.SerialNo,
                        SoftwareName = software.SoftwareName,
                        DateOfPublish = software.DateOfPublish,
                        DateOfExpiry = software.DateOfExpiry,
                        Price = software.Price
                        

                    };
                    ViewBag.softwareAsset = softwareAsset;
                    return View("DisplayTheSearched");

                }
            }
            return View();

        }

        public IActionResult Index()
        {
            List<SoftwareLicense> softwareLicenses = context.SoftwareLicenses.ToList();
            return View(softwareLicenses);
        }
        public IActionResult Details(int id)
        {
            SoftwareLicense softwareLicenses = context.SoftwareLicenses.Where(x => x.SerialNo == id).FirstOrDefault();
            return View(softwareLicenses);
        }
    }
}

NET TECHONOLOGY/NET TECHONOLOGY/DbAssetManagement/DbAssetManagement/Views/Shared/ListEmpty.cshtml
@{
    ViewData["Title"] = "ListEmpty";
}

<h1>List Empty Add the values</h1>

NET TECHONOLOGY/NET TECHONOLOGY/DbAssetManagement/DbAssetManagement/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NFound";
}

<h1>Asset not found in the list please enter the correct value</h1>

NET TECHONOLOGY/NET TECHONOLOGY/DbAssetManagement/DbAssetManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DbAssetManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DbAssetManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SoftwareLicense" asp-action="Index">SoftwareLicense</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hardware" asp-action="Index">Hardware</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" asp-controller="Home">Search</a>
                            <span class="caret"></span>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Book" asp-action="Search">Books</a></li>
                                <li><a asp-controller="SoftwareLicense" asp-action="Search">Software License</a></li>
                                <li><a asp-controller="Hardware" asp-action="Search">Hardware</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DbAssetManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>